### PR TITLE
added ability to read toml based config

### PR DESCRIPTION
**Pull request by Cielquan**
`coverage` supports `pyproject.toml` as config source. This plugin cannot use the config it gets from `coverage` when `pyproject.toml` is used.

I adjusted the code to be able to use both configs.

In  `pyproject.toml` you would write it like this:
```toml
[tool.coverage.coverage_conditional_plugin.rules]
py-gte-38 = "sys_version_info >= (3, 8)"
has-mypy = "is_installed('mypy')"
```

### CODE REVIEW

**Comment by Cielquan** [comment]
Do you have an idea how to test this behavior?

I saw that the config `--cov-config=test_project/.coveragerc` is set in `setup.cfg`.

But how to change the config file for two different tests?

**Comment by sobolevn** [comment]
We can run tests twice. Or maybe there's a fixture / pytest plugin for this?

**Comment by Cielquan** [comment]
My initial idea was to use parameterize to run the test twice .. each with a different config file.

The problem is how to change the config while running pytest.

One option would be to use `subprocess` I think but I would rather not do that.

**Comment by Cielquan** [comment]
I think I found a solution .. currently testing/building.

**Comment by Cielquan** [comment]
So I added a  working test :)

**Comment by sobolevn** [comment]
Thanks a lot!

**Comment by Cielquan** [comment]
You are welcome :)

Are you gonna make a new release soon? :grin:

**Comment by sobolevn** [comment]
Yes, probably tomorrow!

**Comment by sobolevn** [comment]
Done! https://github.com/wemake-services/coverage-conditional-plugin/releases/tag/0.3.0

**Pull request merged**
