### PR TITLE
added missing dependency: packaging

### LINKED ISSUE #10: Missing packaging in dependency
The project uses `packaging` but didn't specify it in pyproject.toml as dependency.

Got this stack trace when running coverage
```
Traceback (most recent call last):
  File "C:\Users\Public\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Public\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Public\virtualenvs\gate-py3.7\Scripts\pytest.exe\__main__.py", line 9, in <module>
  File "c:\users\public\virtualenvs\gate-py3.7\lib\site-packages\_pytest\config\__init__.py", line 58, in main
    config = _prepareconfig(args, plugins)
  File "c:\users\public\virtualenvs\gate-py3.7\lib\site-packages\_pytest\config\__init__.py", line 196, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "c:\users\public\virtualenvs\gate-py3.7\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\users\public\virtualenvs\gate-py3.7\lib\site-packages\pluggy\manager.py", line 92, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\users\public\virtualenvs\gate-py3.7\lib\site-packages\pluggy\manager.py", line 86, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "c:\users\public\virtualenvs\gate-py3.7\lib\site-packages\pluggy\callers.py", line 203, in _multicall
    gen.send(outcome)
  File "c:\users\public\virtualenvs\gate-py3.7\lib\site-packages\_pytest\helpconfig.py", line 93, in pytest_cmdline_parse
    config = outcome.get_result()
  File "c:\users\public\virtualenvs\gate-py3.7\lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "c:\users\public\virtualenvs\gate-py3.7\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "c:\users\public\virtualenvs\gate-py3.7\lib\site-packages\_pytest\config\__init__.py", line 675, in pytest_cmdline_parse
    self.parse(args)
  File "c:\users\public\virtualenvs\gate-py3.7\lib\site-packages\_pytest\config\__init__.py", line 845, in parse
    self._preparse(args, addopts=addopts)
  File "c:\users\public\virtualenvs\gate-py3.7\lib\site-packages\_pytest\config\__init__.py", line 809, in _preparse
    early_config=self, args=args, parser=self._parser
  File "c:\users\public\virtualenvs\gate-py3.7\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\users\public\virtualenvs\gate-py3.7\lib\site-packages\pluggy\manager.py", line 92, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\users\public\virtualenvs\gate-py3.7\lib\site-packages\pluggy\manager.py", line 86, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "c:\users\public\virtualenvs\gate-py3.7\lib\site-packages\pluggy\callers.py", line 208, in _multicall
    return outcome.get_result()
  File "c:\users\public\virtualenvs\gate-py3.7\lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "c:\users\public\virtualenvs\gate-py3.7\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "c:\users\public\virtualenvs\gate-py3.7\lib\site-packages\pytest_cov\plugin.py", line 118, in pytest_load_initial_conftests
    plugin = CovPlugin(early_config.known_args_namespace, early_config.pluginmanager)
  File "c:\users\public\virtualenvs\gate-py3.7\lib\site-packages\pytest_cov\plugin.py", line 164, in __init__
    self.start(engine.Central)
  File "c:\users\public\virtualenvs\gate-py3.7\lib\site-packages\pytest_cov\plugin.py", line 186, in start
    self.cov_controller.start()
  File "c:\users\public\virtualenvs\gate-py3.7\lib\site-packages\pytest_cov\engine.py", line 189, in start
    self.cov.erase()
  File "c:\users\public\virtualenvs\gate-py3.7\lib\site-packages\coverage\control.py", line 568, in erase
    self._init()
  File "c:\users\public\virtualenvs\gate-py3.7\lib\site-packages\coverage\control.py", line 268, in _init
    self._plugins = Plugins.load_plugins(self.config.plugins, self.config, self._debug)
  File "c:\users\public\virtualenvs\gate-py3.7\lib\site-packages\coverage\plugin_support.py", line 41, in load_plugins
    __import__(module)
  File "c:\users\public\virtualenvs\gate-py3.7\lib\site-packages\coverage_conditional_plugin\__init__.py", line 10, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging'
```

### PR DESCRIPTION
**Pull request by Cielquan**
Resolves #10

### CODE REVIEW

**Comment by sobolevn** [comment]
Thanks a lot!

**Comment by Cielquan** [comment]
Will you release 0.4.0 or 0.3.1 ? :)

**Comment by sobolevn** [comment]
Yes, 0.3.1 seems appropriate. I will do it soon! 👍

**Comment by Cielquan** [comment]
May I ask when you plan to release 0.3.1 ? :)

**Comment by sobolevn** [comment]
Done! Sorry for the delay.

**Comment by Cielquan** [comment]
TYVM

**Pull request merged**
